void Straight(){
  myssc.beginGroupCommand(SSC32_CMDGRP_TYPE_SERVO_MOVEMENT);
  myssc.servoMoveTime(21,dePos_L[0],actSpeed);
  myssc.servoMoveTime(22,dePos_L[1],actSpeed);
  myssc.servoMoveTime(23,dePos_L[2],actSpeed);
  myssc.servoMoveTime(24,dePos_L[3],actSpeed);
  myssc.servoMoveTime(25,dePos_L[4],actSpeed);
  myssc.servoMoveTime(26,dePos_L[5],actSpeed);
  myssc.servoMoveTime(28,dePos_L[6],actSpeed);
  myssc.servoMoveTime(29,dePos_L[7],actSpeed);
  myssc.servoMoveTime(5,dePos_R[0],actSpeed);
  myssc.servoMoveTime(6,dePos_R[1],actSpeed);
  myssc.servoMoveTime(7,dePos_R[2],actSpeed);
  myssc.servoMoveTime(8,dePos_R[3],actSpeed);
  myssc.servoMoveTime(9,dePos_R[4],actSpeed);
  myssc.servoMoveTime(10,dePos_R[5],actSpeed);
  myssc.servoMoveTime(12,dePos_R[6],actSpeed);
  myssc.servoMoveTime(13,dePos_R[7],actSpeed);
  myssc.endGroupCommand();
  delay(actSpeed);
  myssc.beginGroupCommand(SSC32_CMDGRP_TYPE_SERVO_MOVEMENT);
  myssc.servoMoveTime(21,dePos_L[0],actSpeed);
  myssc.servoMoveTime(22,dePos_L[1],actSpeed);
  myssc.servoMoveTime(23,dePos_L[2],actSpeed);
  myssc.servoMoveTime(24,dePos_L[3],actSpeed);
  myssc.servoMoveTime(25,dePos_L[4],actSpeed);
  myssc.servoMoveTime(26,dePos_L[5],actSpeed);
  myssc.servoMoveTime(28,dePos_L[6],actSpeed);
  myssc.servoMoveTime(29,dePos_L[7],actSpeed);
  myssc.servoMoveTime(5,dePos_R[0],actSpeed);
  myssc.servoMoveTime(6,dePos_R[1],actSpeed);
  myssc.servoMoveTime(7,dePos_R[2],actSpeed);
  myssc.servoMoveTime(8,dePos_R[3],actSpeed);
  myssc.servoMoveTime(9,dePos_R[4],actSpeed);
  myssc.servoMoveTime(10,dePos_R[5],actSpeed);
  myssc.servoMoveTime(12,dePos_R[6],actSpeed);
  myssc.servoMoveTime(13,dePos_R[7],actSpeed);
  myssc.endGroupCommand();
  delay(actSpeed);
}
void turnLeft(){
  myssc.beginGroupCommand(SSC32_CMDGRP_TYPE_SERVO_MOVEMENT);
  myssc.servoMoveTime(21,dePos_L[0],actSpeed);
  myssc.servoMoveTime(22,dePos_L[1],actSpeed);
  myssc.servoMoveTime(23,dePos_L[2],actSpeed);
  myssc.servoMoveTime(24,dePos_L[3],actSpeed);
  myssc.servoMoveTime(25,dePos_L[4],actSpeed);
  myssc.servoMoveTime(26,dePos_L[5],actSpeed);
  myssc.servoMoveTime(28,dePos_L[6],actSpeed);
  myssc.servoMoveTime(29,dePos_L[7],actSpeed);
  myssc.servoMoveTime(5,dePos_R[0],actSpeed);
  myssc.servoMoveTime(6,dePos_R[1],actSpeed);
  myssc.servoMoveTime(7,dePos_R[2],actSpeed);
  myssc.servoMoveTime(8,dePos_R[3],actSpeed);
  myssc.servoMoveTime(9,dePos_R[4],actSpeed);
  myssc.servoMoveTime(10,dePos_R[5],actSpeed);
  myssc.servoMoveTime(12,dePos_R[6],actSpeed);
  myssc.servoMoveTime(13,dePos_R[7],actSpeed);
  myssc.endGroupCommand();
  delay(actSpeed);
  myssc.beginGroupCommand(SSC32_CMDGRP_TYPE_SERVO_MOVEMENT);
  myssc.servoMoveTime(21,dePos_L[0],actSpeed);
  myssc.servoMoveTime(22,dePos_L[1],actSpeed);
  myssc.servoMoveTime(23,dePos_L[2],actSpeed);
  myssc.servoMoveTime(24,dePos_L[3],actSpeed);
  myssc.servoMoveTime(25,dePos_L[4],actSpeed);
  myssc.servoMoveTime(26,dePos_L[5],actSpeed);
  myssc.servoMoveTime(28,dePos_L[6],actSpeed);
  myssc.servoMoveTime(29,dePos_L[7],actSpeed);
  myssc.servoMoveTime(5,dePos_R[0],actSpeed);
  myssc.servoMoveTime(6,dePos_R[1],actSpeed);
  myssc.servoMoveTime(7,dePos_R[2],actSpeed);
  myssc.servoMoveTime(8,dePos_R[3],actSpeed);
  myssc.servoMoveTime(9,dePos_R[4],actSpeed);
  myssc.servoMoveTime(10,dePos_R[5],actSpeed);
  myssc.servoMoveTime(12,dePos_R[6],actSpeed);
  myssc.servoMoveTime(13,dePos_R[7],actSpeed);
  myssc.endGroupCommand();
  delay(actSpeed);
}
void turnRight(){
  myssc.beginGroupCommand(SSC32_CMDGRP_TYPE_SERVO_MOVEMENT);
  myssc.servoMoveTime(21,dePos_L[0],actSpeed);
  myssc.servoMoveTime(22,dePos_L[1],actSpeed);
  myssc.servoMoveTime(23,dePos_L[2],actSpeed);
  myssc.servoMoveTime(24,dePos_L[3],actSpeed);
  myssc.servoMoveTime(25,dePos_L[4],actSpeed);
  myssc.servoMoveTime(26,dePos_L[5],actSpeed);
  myssc.servoMoveTime(28,dePos_L[6],actSpeed);
  myssc.servoMoveTime(29,dePos_L[7],actSpeed);
  myssc.servoMoveTime(5,dePos_R[0],actSpeed);
  myssc.servoMoveTime(6,dePos_R[1],actSpeed);
  myssc.servoMoveTime(7,dePos_R[2],actSpeed);
  myssc.servoMoveTime(8,dePos_R[3],actSpeed);
  myssc.servoMoveTime(9,dePos_R[4],actSpeed);
  myssc.servoMoveTime(10,dePos_R[5],actSpeed);
  myssc.servoMoveTime(12,dePos_R[6],actSpeed);
  myssc.servoMoveTime(13,dePos_R[7],actSpeed);
  myssc.endGroupCommand();
  delay(actSpeed);
  myssc.beginGroupCommand(SSC32_CMDGRP_TYPE_SERVO_MOVEMENT);
  myssc.servoMoveTime(21,dePos_L[0],actSpeed);
  myssc.servoMoveTime(22,dePos_L[1],actSpeed);
  myssc.servoMoveTime(23,dePos_L[2],actSpeed);
  myssc.servoMoveTime(24,dePos_L[3],actSpeed);
  myssc.servoMoveTime(25,dePos_L[4],actSpeed);
  myssc.servoMoveTime(26,dePos_L[5],actSpeed);
  myssc.servoMoveTime(28,dePos_L[6],actSpeed);
  myssc.servoMoveTime(29,dePos_L[7],actSpeed);
  myssc.servoMoveTime(5,dePos_R[0],actSpeed);
  myssc.servoMoveTime(6,dePos_R[1],actSpeed);
  myssc.servoMoveTime(7,dePos_R[2],actSpeed);
  myssc.servoMoveTime(8,dePos_R[3],actSpeed);
  myssc.servoMoveTime(9,dePos_R[4],actSpeed);
  myssc.servoMoveTime(10,dePos_R[5],actSpeed);
  myssc.servoMoveTime(12,dePos_R[6],actSpeed);
  myssc.servoMoveTime(13,dePos_R[7],actSpeed);
  myssc.endGroupCommand();
  delay(actSpeed);
}
void walk(int dir){
  switch (dir) {
    case 8:
      Straight();
      break;
    case 7:
      turnLeft();
      break;
    case 9:
      turnRight();
      break;
  }
  delay(1000);
}
